/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// AddParcelData
    /// </summary>
    [DataContract]
        public partial class AddParcelData :  IEquatable<AddParcelData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddParcelData" /> class.
        /// </summary>
        /// <param name="addParcelData">addParcelData.</param>
        /// <param name="addParcelDataServices">addParcelDataServices.</param>
        public AddParcelData(ParcelParams addParcelData = default(ParcelParams), Services addParcelDataServices = default(Services))
        {
            this._AddParcelData = addParcelData;
            this.AddParcelDataServices = addParcelDataServices;
        }
        
        /// <summary>
        /// Gets or Sets _AddParcelData
        /// </summary>
        [DataMember(Name="addParcelData", EmitDefaultValue=false)]
        public ParcelParams _AddParcelData { get; set; }

        /// <summary>
        /// Gets or Sets AddParcelDataServices
        /// </summary>
        [DataMember(Name="addParcelDataServices", EmitDefaultValue=false)]
        public Services AddParcelDataServices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddParcelData {\n");
            sb.Append("  _AddParcelData: ").Append(_AddParcelData).Append("\n");
            sb.Append("  AddParcelDataServices: ").Append(AddParcelDataServices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddParcelData);
        }

        /// <summary>
        /// Returns true if AddParcelData instances are equal
        /// </summary>
        /// <param name="input">Instance of AddParcelData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddParcelData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._AddParcelData == input._AddParcelData ||
                    (this._AddParcelData != null &&
                    this._AddParcelData.Equals(input._AddParcelData))
                ) && 
                (
                    this.AddParcelDataServices == input.AddParcelDataServices ||
                    (this.AddParcelDataServices != null &&
                    this.AddParcelDataServices.Equals(input.AddParcelDataServices))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._AddParcelData != null)
                    hashCode = hashCode * 59 + this._AddParcelData.GetHashCode();
                if (this.AddParcelDataServices != null)
                    hashCode = hashCode * 59 + this.AddParcelDataServices.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
