/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// Asynchronous header for B2B response
    /// </summary>
    [DataContract]
        public partial class AsyncResponse :  IEquatable<AsyncResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsyncResponse" /> class.
        /// </summary>
        /// <param name="idTransaction">idTransaction.</param>
        public AsyncResponse(string idTransaction = default(string))
        {
            this.IdTransaction = idTransaction;
        }
        
        /// <summary>
        /// Gets or Sets IdTransaction
        /// </summary>
        [DataMember(Name="idTransaction", EmitDefaultValue=false)]
        public string IdTransaction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsyncResponse {\n");
            sb.Append("  IdTransaction: ").Append(IdTransaction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AsyncResponse);
        }

        /// <summary>
        /// Returns true if AsyncResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AsyncResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsyncResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdTransaction == input.IdTransaction ||
                    (this.IdTransaction != null &&
                    this.IdTransaction.Equals(input.IdTransaction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdTransaction != null)
                    hashCode = hashCode * 59 + this.IdTransaction.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
