/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// LetterPrintingResponse
    /// </summary>
    [DataContract]
        public partial class LetterPrintingResponse :  IEquatable<LetterPrintingResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LetterPrintingResponse" /> class.
        /// </summary>
        /// <param name="printingHeaderResult">printingHeaderResult.</param>
        /// <param name="printingDataResult">printingDataResult.</param>
        public LetterPrintingResponse(PrintingHeaderResult printingHeaderResult = default(PrintingHeaderResult), byte[] printingDataResult = default(byte[]))
        {
            this.PrintingHeaderResult = printingHeaderResult;
            this.PrintingDataResult = printingDataResult;
        }
        
        /// <summary>
        /// Gets or Sets PrintingHeaderResult
        /// </summary>
        [DataMember(Name="printingHeaderResult", EmitDefaultValue=false)]
        public PrintingHeaderResult PrintingHeaderResult { get; set; }

        /// <summary>
        /// Gets or Sets PrintingDataResult
        /// </summary>
        [DataMember(Name="printingDataResult", EmitDefaultValue=false)]
        public byte[] PrintingDataResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LetterPrintingResponse {\n");
            sb.Append("  PrintingHeaderResult: ").Append(PrintingHeaderResult).Append("\n");
            sb.Append("  PrintingDataResult: ").Append(PrintingDataResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LetterPrintingResponse);
        }

        /// <summary>
        /// Returns true if LetterPrintingResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LetterPrintingResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LetterPrintingResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PrintingHeaderResult == input.PrintingHeaderResult ||
                    (this.PrintingHeaderResult != null &&
                    this.PrintingHeaderResult.Equals(input.PrintingHeaderResult))
                ) && 
                (
                    this.PrintingDataResult == input.PrintingDataResult ||
                    (this.PrintingDataResult != null &&
                    this.PrintingDataResult.Equals(input.PrintingDataResult))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PrintingHeaderResult != null)
                    hashCode = hashCode * 59 + this.PrintingHeaderResult.GetHashCode();
                if (this.PrintingDataResult != null)
                    hashCode = hashCode * 59 + this.PrintingDataResult.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
