/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// LocationData
    /// </summary>
    [DataContract]
        public partial class LocationData :  IEquatable<LocationData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocationData" /> class.
        /// </summary>
        /// <param name="locationNumber">locationNumber.</param>
        /// <param name="locationDataResponseList">locationDataResponseList.</param>
        public LocationData(int? locationNumber = default(int?), List<LocationDataResponse> locationDataResponseList = default(List<LocationDataResponse>))
        {
            this.LocationNumber = locationNumber;
            this.LocationDataResponseList = locationDataResponseList;
        }
        
        /// <summary>
        /// Gets or Sets LocationNumber
        /// </summary>
        [DataMember(Name="locationNumber", EmitDefaultValue=false)]
        public int? LocationNumber { get; set; }

        /// <summary>
        /// Gets or Sets LocationDataResponseList
        /// </summary>
        [DataMember(Name="locationDataResponseList", EmitDefaultValue=false)]
        public List<LocationDataResponse> LocationDataResponseList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LocationData {\n");
            sb.Append("  LocationNumber: ").Append(LocationNumber).Append("\n");
            sb.Append("  LocationDataResponseList: ").Append(LocationDataResponseList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LocationData);
        }

        /// <summary>
        /// Returns true if LocationData instances are equal
        /// </summary>
        /// <param name="input">Instance of LocationData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LocationData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LocationNumber == input.LocationNumber ||
                    (this.LocationNumber != null &&
                    this.LocationNumber.Equals(input.LocationNumber))
                ) && 
                (
                    this.LocationDataResponseList == input.LocationDataResponseList ||
                    this.LocationDataResponseList != null &&
                    input.LocationDataResponseList != null &&
                    this.LocationDataResponseList.SequenceEqual(input.LocationDataResponseList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LocationNumber != null)
                    hashCode = hashCode * 59 + this.LocationNumber.GetHashCode();
                if (this.LocationDataResponseList != null)
                    hashCode = hashCode * 59 + this.LocationDataResponseList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
