/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// PrintingHeader
    /// </summary>
    [DataContract]
        public partial class PrintingHeader :  IEquatable<PrintingHeader>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrintingHeader" /> class.
        /// </summary>
        /// <param name="customerID">customerID (required).</param>
        /// <param name="contractNumber">contractNumber.</param>
        /// <param name="idForm">idForm.</param>
        /// <param name="shiftHorizontal">shiftHorizontal (required).</param>
        /// <param name="shiftVertical">shiftVertical (required).</param>
        /// <param name="position">position.</param>
        public PrintingHeader(string customerID = default(string), string contractNumber = default(string), int? idForm = default(int?), decimal? shiftHorizontal = default(decimal?), decimal? shiftVertical = default(decimal?), decimal? position = default(decimal?))
        {
            // to ensure "customerID" is required (not null)
            if (customerID == null)
            {
                throw new InvalidDataException("customerID is a required property for PrintingHeader and cannot be null");
            }
            else
            {
                this.CustomerID = customerID;
            }
            // to ensure "shiftHorizontal" is required (not null)
            if (shiftHorizontal == null)
            {
                throw new InvalidDataException("shiftHorizontal is a required property for PrintingHeader and cannot be null");
            }
            else
            {
                this.ShiftHorizontal = shiftHorizontal;
            }
            // to ensure "shiftVertical" is required (not null)
            if (shiftVertical == null)
            {
                throw new InvalidDataException("shiftVertical is a required property for PrintingHeader and cannot be null");
            }
            else
            {
                this.ShiftVertical = shiftVertical;
            }
            this.ContractNumber = contractNumber;
            this.IdForm = idForm;
            this.Position = position;
        }
        
        /// <summary>
        /// Gets or Sets CustomerID
        /// </summary>
        [DataMember(Name="customerID", EmitDefaultValue=false)]
        public string CustomerID { get; set; }

        /// <summary>
        /// Gets or Sets ContractNumber
        /// </summary>
        [DataMember(Name="contractNumber", EmitDefaultValue=false)]
        public string ContractNumber { get; set; }

        /// <summary>
        /// Gets or Sets IdForm
        /// </summary>
        [DataMember(Name="idForm", EmitDefaultValue=false)]
        public int? IdForm { get; set; }

        /// <summary>
        /// Gets or Sets ShiftHorizontal
        /// </summary>
        [DataMember(Name="shiftHorizontal", EmitDefaultValue=false)]
        public decimal? ShiftHorizontal { get; set; }

        /// <summary>
        /// Gets or Sets ShiftVertical
        /// </summary>
        [DataMember(Name="shiftVertical", EmitDefaultValue=false)]
        public decimal? ShiftVertical { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name="position", EmitDefaultValue=false)]
        public decimal? Position { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PrintingHeader {\n");
            sb.Append("  CustomerID: ").Append(CustomerID).Append("\n");
            sb.Append("  ContractNumber: ").Append(ContractNumber).Append("\n");
            sb.Append("  IdForm: ").Append(IdForm).Append("\n");
            sb.Append("  ShiftHorizontal: ").Append(ShiftHorizontal).Append("\n");
            sb.Append("  ShiftVertical: ").Append(ShiftVertical).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PrintingHeader);
        }

        /// <summary>
        /// Returns true if PrintingHeader instances are equal
        /// </summary>
        /// <param name="input">Instance of PrintingHeader to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrintingHeader input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomerID == input.CustomerID ||
                    (this.CustomerID != null &&
                    this.CustomerID.Equals(input.CustomerID))
                ) && 
                (
                    this.ContractNumber == input.ContractNumber ||
                    (this.ContractNumber != null &&
                    this.ContractNumber.Equals(input.ContractNumber))
                ) && 
                (
                    this.IdForm == input.IdForm ||
                    (this.IdForm != null &&
                    this.IdForm.Equals(input.IdForm))
                ) && 
                (
                    this.ShiftHorizontal == input.ShiftHorizontal ||
                    (this.ShiftHorizontal != null &&
                    this.ShiftHorizontal.Equals(input.ShiftHorizontal))
                ) && 
                (
                    this.ShiftVertical == input.ShiftVertical ||
                    (this.ShiftVertical != null &&
                    this.ShiftVertical.Equals(input.ShiftVertical))
                ) && 
                (
                    this.Position == input.Position ||
                    (this.Position != null &&
                    this.Position.Equals(input.Position))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomerID != null)
                    hashCode = hashCode * 59 + this.CustomerID.GetHashCode();
                if (this.ContractNumber != null)
                    hashCode = hashCode * 59 + this.ContractNumber.GetHashCode();
                if (this.IdForm != null)
                    hashCode = hashCode * 59 + this.IdForm.GetHashCode();
                if (this.ShiftHorizontal != null)
                    hashCode = hashCode * 59 + this.ShiftHorizontal.GetHashCode();
                if (this.ShiftVertical != null)
                    hashCode = hashCode * 59 + this.ShiftVertical.GetHashCode();
                if (this.Position != null)
                    hashCode = hashCode * 59 + this.Position.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
