/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// ResultParcelCustomsGoodsItem
    /// </summary>
    [DataContract]
        public partial class ResultParcelCustomsGoodsItem :  IEquatable<ResultParcelCustomsGoodsItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResultParcelCustomsGoodsItem" /> class.
        /// </summary>
        /// <param name="sequence">sequence.</param>
        /// <param name="customGoodsResponse">customGoodsResponse.</param>
        public ResultParcelCustomsGoodsItem(int? sequence = default(int?), List<StatusResponseItem> customGoodsResponse = default(List<StatusResponseItem>))
        {
            this.Sequence = sequence;
            this.CustomGoodsResponse = customGoodsResponse;
        }
        
        /// <summary>
        /// Gets or Sets Sequence
        /// </summary>
        [DataMember(Name="sequence", EmitDefaultValue=false)]
        public int? Sequence { get; set; }

        /// <summary>
        /// Gets or Sets CustomGoodsResponse
        /// </summary>
        [DataMember(Name="customGoodsResponse", EmitDefaultValue=false)]
        public List<StatusResponseItem> CustomGoodsResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResultParcelCustomsGoodsItem {\n");
            sb.Append("  Sequence: ").Append(Sequence).Append("\n");
            sb.Append("  CustomGoodsResponse: ").Append(CustomGoodsResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResultParcelCustomsGoodsItem);
        }

        /// <summary>
        /// Returns true if ResultParcelCustomsGoodsItem instances are equal
        /// </summary>
        /// <param name="input">Instance of ResultParcelCustomsGoodsItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResultParcelCustomsGoodsItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Sequence == input.Sequence ||
                    (this.Sequence != null &&
                    this.Sequence.Equals(input.Sequence))
                ) && 
                (
                    this.CustomGoodsResponse == input.CustomGoodsResponse ||
                    this.CustomGoodsResponse != null &&
                    input.CustomGoodsResponse != null &&
                    this.CustomGoodsResponse.SequenceEqual(input.CustomGoodsResponse)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Sequence != null)
                    hashCode = hashCode * 59 + this.Sequence.GetHashCode();
                if (this.CustomGoodsResponse != null)
                    hashCode = hashCode * 59 + this.CustomGoodsResponse.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
