/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// ResultParcelCustomsDocumentList
    /// </summary>
    [DataContract]
        public partial class ResultParcelCustomsDocumentList :  IEquatable<ResultParcelCustomsDocumentList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResultParcelCustomsDocumentList" /> class.
        /// </summary>
        /// <param name="recordID">recordID.</param>
        /// <param name="customDocumentsResponse">customDocumentsResponse.</param>
        public ResultParcelCustomsDocumentList(string recordID = default(string), List<StatusResponseItem> customDocumentsResponse = default(List<StatusResponseItem>))
        {
            this.RecordID = recordID;
            this.CustomDocumentsResponse = customDocumentsResponse;
        }
        
        /// <summary>
        /// Gets or Sets RecordID
        /// </summary>
        [DataMember(Name="recordID", EmitDefaultValue=false)]
        public string RecordID { get; set; }

        /// <summary>
        /// Gets or Sets CustomDocumentsResponse
        /// </summary>
        [DataMember(Name="customDocumentsResponse", EmitDefaultValue=false)]
        public List<StatusResponseItem> CustomDocumentsResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResultParcelCustomsDocumentList {\n");
            sb.Append("  RecordID: ").Append(RecordID).Append("\n");
            sb.Append("  CustomDocumentsResponse: ").Append(CustomDocumentsResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResultParcelCustomsDocumentList);
        }

        /// <summary>
        /// Returns true if ResultParcelCustomsDocumentList instances are equal
        /// </summary>
        /// <param name="input">Instance of ResultParcelCustomsDocumentList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResultParcelCustomsDocumentList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RecordID == input.RecordID ||
                    (this.RecordID != null &&
                    this.RecordID.Equals(input.RecordID))
                ) && 
                (
                    this.CustomDocumentsResponse == input.CustomDocumentsResponse ||
                    this.CustomDocumentsResponse != null &&
                    input.CustomDocumentsResponse != null &&
                    this.CustomDocumentsResponse.SequenceEqual(input.CustomDocumentsResponse)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RecordID != null)
                    hashCode = hashCode * 59 + this.RecordID.GetHashCode();
                if (this.CustomDocumentsResponse != null)
                    hashCode = hashCode * 59 + this.CustomDocumentsResponse.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
