/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.CzechPost.Client.SwaggerDateConverter;
namespace IO.Swagger.CzechPost.Model
{
    /// <summary>
    /// StatusResponseItem
    /// </summary>
    [DataContract]
        public partial class StatusResponseItem :  IEquatable<StatusResponseItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatusResponseItem" /> class.
        /// </summary>
        /// <param name="responseCode">Code of failure. / Kód chyby. (required).</param>
        /// <param name="responseText">Description of failure. / Popis chyby. (required).</param>
        public StatusResponseItem(int? responseCode = default(int?), string responseText = default(string))
        {
            // to ensure "responseCode" is required (not null)
            if (responseCode == null)
            {
                throw new InvalidDataException("responseCode is a required property for StatusResponseItem and cannot be null");
            }
            else
            {
                this.ResponseCode = responseCode;
            }
            // to ensure "responseText" is required (not null)
            if (responseText == null)
            {
                throw new InvalidDataException("responseText is a required property for StatusResponseItem and cannot be null");
            }
            else
            {
                this.ResponseText = responseText;
            }
        }
        
        /// <summary>
        /// Code of failure. / Kód chyby.
        /// </summary>
        /// <value>Code of failure. / Kód chyby.</value>
        [DataMember(Name="responseCode", EmitDefaultValue=false)]
        public int? ResponseCode { get; set; }

        /// <summary>
        /// Description of failure. / Popis chyby.
        /// </summary>
        /// <value>Description of failure. / Popis chyby.</value>
        [DataMember(Name="responseText", EmitDefaultValue=false)]
        public string ResponseText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StatusResponseItem {\n");
            sb.Append("  ResponseCode: ").Append(ResponseCode).Append("\n");
            sb.Append("  ResponseText: ").Append(ResponseText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StatusResponseItem);
        }

        /// <summary>
        /// Returns true if StatusResponseItem instances are equal
        /// </summary>
        /// <param name="input">Instance of StatusResponseItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatusResponseItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ResponseCode == input.ResponseCode ||
                    (this.ResponseCode != null &&
                    this.ResponseCode.Equals(input.ResponseCode))
                ) && 
                (
                    this.ResponseText == input.ResponseText ||
                    (this.ResponseText != null &&
                    this.ResponseText.Equals(input.ResponseText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ResponseCode != null)
                    hashCode = hashCode * 59 + this.ResponseCode.GetHashCode();
                if (this.ResponseText != null)
                    hashCode = hashCode * 59 + this.ResponseText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
