/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.CzechPost.Client;
using IO.Swagger.CzechPost.Model;

namespace IO.Swagger.CzechPost.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ILocationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create the location
        /// </summary>
        /// <remarks>
        /// Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>LocationCreateResponse</returns>
        LocationCreateResponse CreateLocation (Location body, string idContract);

        /// <summary>
        /// Create the location
        /// </summary>
        /// <remarks>
        /// Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>ApiResponse of LocationCreateResponse</returns>
        ApiResponse<LocationCreateResponse> CreateLocationWithHttpInfo (Location body, string idContract);
        /// <summary>
        /// Delete the location
        /// </summary>
        /// <remarks>
        /// Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns></returns>
        void DeleteLocation (string idContract, int? locationNumber);

        /// <summary>
        /// Delete the location
        /// </summary>
        /// <remarks>
        /// Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteLocationWithHttpInfo (string idContract, int? locationNumber);
        /// <summary>
        /// Get list of location
        /// </summary>
        /// <remarks>
        /// Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>LocationList</returns>
        LocationList GetLocation (string idContract);

        /// <summary>
        /// Get list of location
        /// </summary>
        /// <remarks>
        /// Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>ApiResponse of LocationList</returns>
        ApiResponse<LocationList> GetLocationWithHttpInfo (string idContract);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create the location
        /// </summary>
        /// <remarks>
        /// Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of LocationCreateResponse</returns>
        System.Threading.Tasks.Task<LocationCreateResponse> CreateLocationAsync (Location body, string idContract);

        /// <summary>
        /// Create the location
        /// </summary>
        /// <remarks>
        /// Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of ApiResponse (LocationCreateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LocationCreateResponse>> CreateLocationAsyncWithHttpInfo (Location body, string idContract);
        /// <summary>
        /// Delete the location
        /// </summary>
        /// <remarks>
        /// Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteLocationAsync (string idContract, int? locationNumber);

        /// <summary>
        /// Delete the location
        /// </summary>
        /// <remarks>
        /// Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteLocationAsyncWithHttpInfo (string idContract, int? locationNumber);
        /// <summary>
        /// Get list of location
        /// </summary>
        /// <remarks>
        /// Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of LocationList</returns>
        System.Threading.Tasks.Task<LocationList> GetLocationAsync (string idContract);

        /// <summary>
        /// Get list of location
        /// </summary>
        /// <remarks>
        /// Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of ApiResponse (LocationList)</returns>
        System.Threading.Tasks.Task<ApiResponse<LocationList>> GetLocationAsyncWithHttpInfo (string idContract);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class LocationApi : ILocationApi
    {
        private IO.Swagger.CzechPost.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LocationApi(String basePath)
        {
            this.Configuration = new IO.Swagger.CzechPost.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.CzechPost.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationApi"/> class
        /// </summary>
        /// <returns></returns>
        public LocationApi()
        {
            this.Configuration = IO.Swagger.CzechPost.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.CzechPost.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LocationApi(IO.Swagger.CzechPost.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.CzechPost.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.CzechPost.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.CzechPost.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.CzechPost.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create the location Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>LocationCreateResponse</returns>
        public LocationCreateResponse CreateLocation (Location body, string idContract)
        {
             ApiResponse<LocationCreateResponse> localVarResponse = CreateLocationWithHttpInfo(body, idContract);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create the location Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>ApiResponse of LocationCreateResponse</returns>
        public ApiResponse< LocationCreateResponse > CreateLocationWithHttpInfo (Location body, string idContract)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling LocationApi->CreateLocation");
            // verify the required parameter 'idContract' is set
            if (idContract == null)
                throw new ApiException(400, "Missing required parameter 'idContract' when calling LocationApi->CreateLocation");

            var localVarPath = "/location/idContract/{idContract}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idContract != null) localVarPathParams.Add("idContract", this.Configuration.ApiClient.ParameterToString(idContract)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (Authorization-content-SHA256) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Content-SHA256")))
            {
                localVarHeaderParams["Authorization-Content-SHA256"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Content-SHA256");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateLocation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LocationCreateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (LocationCreateResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LocationCreateResponse)));
        }

        /// <summary>
        /// Create the location Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of LocationCreateResponse</returns>
        public async System.Threading.Tasks.Task<LocationCreateResponse> CreateLocationAsync (Location body, string idContract)
        {
             ApiResponse<LocationCreateResponse> localVarResponse = await CreateLocationAsyncWithHttpInfo(body, idContract);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create the location Create and save the transmitter place, address, bank informations and contatct. / Uloží podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of ApiResponse (LocationCreateResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LocationCreateResponse>> CreateLocationAsyncWithHttpInfo (Location body, string idContract)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling LocationApi->CreateLocation");
            // verify the required parameter 'idContract' is set
            if (idContract == null)
                throw new ApiException(400, "Missing required parameter 'idContract' when calling LocationApi->CreateLocation");

            var localVarPath = "/location/idContract/{idContract}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idContract != null) localVarPathParams.Add("idContract", this.Configuration.ApiClient.ParameterToString(idContract)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (Authorization-content-SHA256) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Content-SHA256")))
            {
                localVarHeaderParams["Authorization-Content-SHA256"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Content-SHA256");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateLocation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LocationCreateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (LocationCreateResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LocationCreateResponse)));
        }

        /// <summary>
        /// Delete the location Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns></returns>
        public void DeleteLocation (string idContract, int? locationNumber)
        {
             DeleteLocationWithHttpInfo(idContract, locationNumber);
        }

        /// <summary>
        /// Delete the location Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteLocationWithHttpInfo (string idContract, int? locationNumber)
        {
            // verify the required parameter 'idContract' is set
            if (idContract == null)
                throw new ApiException(400, "Missing required parameter 'idContract' when calling LocationApi->DeleteLocation");
            // verify the required parameter 'locationNumber' is set
            if (locationNumber == null)
                throw new ApiException(400, "Missing required parameter 'locationNumber' when calling LocationApi->DeleteLocation");

            var localVarPath = "/location/idContract/{idContract}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idContract != null) localVarPathParams.Add("idContract", this.Configuration.ApiClient.ParameterToString(idContract)); // path parameter
            if (locationNumber != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "locationNumber", locationNumber)); // query parameter
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteLocation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Delete the location Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteLocationAsync (string idContract, int? locationNumber)
        {
             await DeleteLocationAsyncWithHttpInfo(idContract, locationNumber);

        }

        /// <summary>
        /// Delete the location Delete the transmitter place, address, bank informations and contatct. / Zruší podací místo včetně adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <param name="locationNumber">Number of transmitter place. / Číslo podacího místa.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteLocationAsyncWithHttpInfo (string idContract, int? locationNumber)
        {
            // verify the required parameter 'idContract' is set
            if (idContract == null)
                throw new ApiException(400, "Missing required parameter 'idContract' when calling LocationApi->DeleteLocation");
            // verify the required parameter 'locationNumber' is set
            if (locationNumber == null)
                throw new ApiException(400, "Missing required parameter 'locationNumber' when calling LocationApi->DeleteLocation");

            var localVarPath = "/location/idContract/{idContract}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idContract != null) localVarPathParams.Add("idContract", this.Configuration.ApiClient.ParameterToString(idContract)); // path parameter
            if (locationNumber != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "locationNumber", locationNumber)); // query parameter
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteLocation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Get list of location Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>LocationList</returns>
        public LocationList GetLocation (string idContract)
        {
             ApiResponse<LocationList> localVarResponse = GetLocationWithHttpInfo(idContract);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get list of location Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>ApiResponse of LocationList</returns>
        public ApiResponse< LocationList > GetLocationWithHttpInfo (string idContract)
        {
            // verify the required parameter 'idContract' is set
            if (idContract == null)
                throw new ApiException(400, "Missing required parameter 'idContract' when calling LocationApi->GetLocation");

            var localVarPath = "/location/idContract/{idContract}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idContract != null) localVarPathParams.Add("idContract", this.Configuration.ApiClient.ParameterToString(idContract)); // path parameter
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLocation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LocationList>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (LocationList) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LocationList)));
        }

        /// <summary>
        /// Get list of location Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of LocationList</returns>
        public async System.Threading.Tasks.Task<LocationList> GetLocationAsync (string idContract)
        {
             ApiResponse<LocationList> localVarResponse = await GetLocationAsyncWithHttpInfo(idContract);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get list of location Get the list transmitter places, addresses, bank informations and contacts. / Seznam podacích míst, adres, bankovních spojení a kontaktů.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idContract">ID CCK of submitter. / ID CČK složky podavatele.</param>
        /// <returns>Task of ApiResponse (LocationList)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LocationList>> GetLocationAsyncWithHttpInfo (string idContract)
        {
            // verify the required parameter 'idContract' is set
            if (idContract == null)
                throw new ApiException(400, "Missing required parameter 'idContract' when calling LocationApi->GetLocation");

            var localVarPath = "/location/idContract/{idContract}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idContract != null) localVarPathParams.Add("idContract", this.Configuration.ApiClient.ParameterToString(idContract)); // path parameter
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLocation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LocationList>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (LocationList) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LocationList)));
        }

    }
}
