/* 
 * B2B-ZSKService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.CzechPost.Client;
using IO.Swagger.CzechPost.Model;

namespace IO.Swagger.CzechPost.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IStatusInfoApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get consignment current status by ID
        /// </summary>
        /// <remarks>
        /// Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>ParcelStatusCurrent</returns>
        ParcelStatusCurrent GetParcelStatusCurrent (string idParcel);

        /// <summary>
        /// Get consignment current status by ID
        /// </summary>
        /// <remarks>
        /// Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>ApiResponse of ParcelStatusCurrent</returns>
        ApiResponse<ParcelStatusCurrent> GetParcelStatusCurrentWithHttpInfo (string idParcel);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get consignment current status by ID
        /// </summary>
        /// <remarks>
        /// Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>Task of ParcelStatusCurrent</returns>
        System.Threading.Tasks.Task<ParcelStatusCurrent> GetParcelStatusCurrentAsync (string idParcel);

        /// <summary>
        /// Get consignment current status by ID
        /// </summary>
        /// <remarks>
        /// Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </remarks>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>Task of ApiResponse (ParcelStatusCurrent)</returns>
        System.Threading.Tasks.Task<ApiResponse<ParcelStatusCurrent>> GetParcelStatusCurrentAsyncWithHttpInfo (string idParcel);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class StatusInfoApi : IStatusInfoApi
    {
        private IO.Swagger.CzechPost.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatusInfoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StatusInfoApi(String basePath)
        {
            this.Configuration = new IO.Swagger.CzechPost.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.CzechPost.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatusInfoApi"/> class
        /// </summary>
        /// <returns></returns>
        public StatusInfoApi()
        {
            this.Configuration = IO.Swagger.CzechPost.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.CzechPost.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatusInfoApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StatusInfoApi(IO.Swagger.CzechPost.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.CzechPost.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.CzechPost.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.CzechPost.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.CzechPost.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get consignment current status by ID Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>ParcelStatusCurrent</returns>
        public ParcelStatusCurrent GetParcelStatusCurrent (string idParcel)
        {
             ApiResponse<ParcelStatusCurrent> localVarResponse = GetParcelStatusCurrentWithHttpInfo(idParcel);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get consignment current status by ID Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>ApiResponse of ParcelStatusCurrent</returns>
        public ApiResponse< ParcelStatusCurrent > GetParcelStatusCurrentWithHttpInfo (string idParcel)
        {
            // verify the required parameter 'idParcel' is set
            if (idParcel == null)
                throw new ApiException(400, "Missing required parameter 'idParcel' when calling StatusInfoApi->GetParcelStatusCurrent");

            var localVarPath = "/parcelStatuses/current/idParcel/{idParcel}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idParcel != null) localVarPathParams.Add("idParcel", this.Configuration.ApiClient.ParameterToString(idParcel)); // path parameter
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetParcelStatusCurrent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ParcelStatusCurrent>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ParcelStatusCurrent) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ParcelStatusCurrent)));
        }

        /// <summary>
        /// Get consignment current status by ID Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>Task of ParcelStatusCurrent</returns>
        public async System.Threading.Tasks.Task<ParcelStatusCurrent> GetParcelStatusCurrentAsync (string idParcel)
        {
             ApiResponse<ParcelStatusCurrent> localVarResponse = await GetParcelStatusCurrentAsyncWithHttpInfo(idParcel);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get consignment current status by ID Get the current status of the consignment - search by id of the consignment. / Předá aktuální stav zásilky - vyhledání dle id zásilky.
        /// </summary>
        /// <exception cref="IO.Swagger.CzechPost.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idParcel">ID of consignment/parcel. / ID zásilky.</param>
        /// <returns>Task of ApiResponse (ParcelStatusCurrent)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ParcelStatusCurrent>> GetParcelStatusCurrentAsyncWithHttpInfo (string idParcel)
        {
            // verify the required parameter 'idParcel' is set
            if (idParcel == null)
                throw new ApiException(400, "Missing required parameter 'idParcel' when calling StatusInfoApi->GetParcelStatusCurrent");

            var localVarPath = "/parcelStatuses/current/idParcel/{idParcel}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (idParcel != null) localVarPathParams.Add("idParcel", this.Configuration.ApiClient.ParameterToString(idParcel)); // path parameter
            // authentication (Api-Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Token")))
            {
                localVarHeaderParams["Api-Token"] = this.Configuration.GetApiKeyWithPrefix("Api-Token");
            }
            // authentication (Authorization-Timestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp")))
            {
                localVarHeaderParams["Authorization-Timestamp"] = this.Configuration.GetApiKeyWithPrefix("Authorization-Timestamp");
            }
            // authentication (HMAC_SHA256_Auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetParcelStatusCurrent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ParcelStatusCurrent>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ParcelStatusCurrent) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ParcelStatusCurrent)));
        }

    }
}
